Repository IABorges/Projeto-2, pull requests merged in 2024-04, with the labels that each got.

#14 Issue 4 documentação
  README.md
Labels: documentation

#12 #define feito
  tarefas.h
Labels: bug

#9 Issue 3 correção de bug
  main.c
Labels: bug

#13 nos f targets de categoria e descrição adicionei um valor nulo no / n
  tarefas.c
Labels: bug

#16 1 issue 1 quebra de linha
  tarefas.c
Labels: bug, enhancement

#17 Issue 8 funcionalidade extra 3
  main.c
  tarefas.c
  tarefas.h
Labels: enhancement
